name: Prod CI

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    environment: prod
    env:
      REACT_APP_DEPLOY_TARGET: "PROD"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: CI=false yarn workspace dapp build --if-present
    - run: yarn workspace services build --if-present
    - run: cp -r packages/dapp/dist/build/ packages/services/dist/
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/737226828112/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-prod@kernel-services-prod.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - run: yarn workspace services deploy:prod